### ISSUE TITLE
It might be useful to add date fields

### ISSUE THREAD

**Issue by dstaulcu** [Neo23x0/sigma#15]
It might be useful to date fields like date rule created or dated rule updated.   That way, folks who use this down stream can run (potentially expensive) searches on old data with only new/updated rules.

**Comment by thomaspatzke** [comment]
Personally I don't like to keep such metadata inside of the rules because this is a typical reason for inconsistent data. People simply forget to keep such data updated or to add it in new rules. On the other side, the whole functionality only works when such attributes are set in the complete rule set.

I think it should be possible to write a tool that derives such data from the version control metadata (Git commits).

@Neo23x0 what do you think about it?
