### ISSUE TITLE
sigmac: OSSEC backend

### ISSUE THREAD

**Issue by thomaspatzke** [Neo23x0/sigma#52]
Generate OSSEC rules from sigmac

Relevant documentation:
[OSSEC Documentation](https://ossec.github.io/docs/)
[Rules and Decoders](https://ossec.github.io/docs/manual/rules-decoders/index.html)
[Rule Syntax](https://ossec.github.io/docs/syntax/head_rules.html)

Inspired by #51

**Comment by borbelyau** [comment]
I will help this feature

**Comment by SanWieb** [comment]
Hi all,

I have created a script named sigWah to automate the conversion between Sigma and Wazuh rules, it is not fully automatic and still in a very early stage but it will save a lot of time. 
Due to lack of time I did not migrate it to a Sigma backend, maybe in the future I will. 

https://github.com/SanWieb/sigWah
