### ISSUE TITLE
win_possible_dc_sync.yml

### ISSUE THREAD

**Issue by Chak092** [Neo23x0/sigma#726]
Hi guys,

It's maybe a confusion but this detection logic concern DC Shadow with the creation of Global Catalog object and not DC Sync. Is it possible to rename this rule ?

Thanks

**Comment by Karneades** [comment]
In the referenced links, e.g. the gist from Benjamin Delpy [dcsync-dcshadow.splunk](https://gist.github.com/gentilkiwi/dcc132457408cf11ad2061340dcb53c2#file-dcsync-dcshadow-splunk-L16) it's called `dcsync-dcshadow` => would **win_possible_dcsync_dcshadow.yml** be good?

And while updating the rule, then we should remove the reference to https://jsecurity101.com/. It's not reachable any more and [not found in the web archive](https://web.archive.org/web/*/https://jsecurity101.com/2019/Syncing-into-the-Shadows). https://blog.alsid.eu/dcshadow-explained-4510f52fc19d may be worth adding instead.

Similarly, this rule should be renamed too to reflect mimikatz in the name: [win_dcsync.yml](https://github.com/Neo23x0/sigma/blob/ec5bb710499caae6667c7f7311ca9e92c03b9039/rules/windows/builtin/win_dcsync.yml) => **win_mimikatz_dcsync.yml** oder change the title and description and remove mimikatz.

https://github.com/Neo23x0/sigma/blob/ec5bb710499caae6667c7f7311ca9e92c03b9039/rules/windows/builtin/win_dcsync.yml#L1


@Chak092 Are you able to provide the needed PR to reflect your proposed changes? Otherwise, if the renaming above is ok I can make the needed PRs of course too.

**Comment by Chak092** [comment]
The rule present by Benjamin Delpy covered Dcsync & Dcshadow but the sigma rule named win_possible_dc_sync.yml covered only Dcshadow so the name dcsync is not really correct. The other way that we can use to detect Dcshadow is to use this logic : EventCode=5136 LDAP_Display_Name=servicePrincipalName Value="GC/*"

**Comment by Chak092** [comment]
I will create an another rule to cover this point or modify the existant if you like.

**Comment by Karneades** [comment]
You could add this additional detection in the existing rule and rename it accordingly.

**Comment by Karneades** [comment]
See https://github.com/Neo23x0/sigma/pull/729.
