### ISSUE TITLE
wrong output elastic search watcher

### ISSUE THREAD

**Issue by gsdt** [Neo23x0/sigma#789]
I run following command:
`./tools/sigmac -t xpack-watcher -c winlogbeat rules/windows/process_creation/win_exploit_cve_2019_1388.yml`

and sigmac return to me:
```
curl -s -XPUT -H 'Content-Type: application/json' --data-binary @- localhost:9200/_watcher/watch/02e0b2ea-a597-428e-b04a-af6a1a403e5c <<EOF
{
  "metadata": {
    "title": "Exploiting CVE-2019-1388",
    "description": "Detects an explotation attempt in which the UAC consent dialogue is used to invoke an Internet Explorer process running as LOCAL_SYSTEM",
    "tags": [
      "attack.privilege_escalation",
      "attack.t1068"
    ],
    "query": "((winlog.event_data.ParentImage.keyword:*\\\\consent.exe AND winlog.event_data.Image.keyword:*\\\\iexplore.exe AND winlog.event_data.CommandLine.keyword:*\\ http*) AND (IntegrityLevel:\"System\" OR winlog.event_data.User:\"NT\\ AUTHORITY\\\\SYSTEM\"))"
  },
  "trigger": {
    "schedule": {
      "interval": "30m"
    }
  },
  "input": {
    "search": {
      "request": {
        "body": {
          "size": 0,
          "query": {
            "bool": {
              "must": [
                {
                  "query_string": {
                    "query": "((winlog.event_data.ParentImage.keyword:*\\\\consent.exe AND winlog.event_data.Image.keyword:*\\\\iexplore.exe AND winlog.event_data.CommandLine.keyword:*\\ http*) AND (IntegrityLevel:\"System\" OR winlog.event_data.User:\"NT\\ AUTHORITY\\\\SYSTEM\"))",
                    "analyze_wildcard": true
                  }
                }
              ],
              "filter": {
                "range": {
                  "timestamp": {
                    "gte": "now-30m/m"
                  }
                }
              }
            }
          }
        },
        "indices": [
          "winlogbeat-*"
        ]
      }
    }
  },
  "condition": {
    "compare": {
      "ctx.payload.hits.total": {
        "not_eq": 0
      }
    }
  },
  "actions": {
    "send_email": {
      "email": {
        "to": "root@localhost",
        "subject": "Sigma Rule 'Exploiting CVE-2019-1388'",
        "body": "Hits:\n{{#ctx.payload.hits.hits}}{{_source}}\n================================================================================\n{{/ctx.payload.hits.hits}}",
        "attachments": {
          "data.json": {
            "data": {
              "format": "json"
            }
          }
        }
      }
    }
  }
}
```

This watcher will never fire. The *problem* is the field `winlog.event_data.ParentImage.keyword` in *query_string* doesn't exist. I expect it will only show `winlog.event_data.ParentImage` (without `keyword`).

How to solve this problem?

**Comment by neu5ron** [comment]
@gsdt  there are a few elastic mapping variations, I will work on documenting. For now, you have two options:

1. because analyzed fields are removed by Elastic mapping there are no case insensitive options in elasticsearch other than to use regex, thus in order to prevent easy bypasses / detection evasions, elasticsearch requires regex. Add the follow to your command:
`--backend-option keyword_field='' --backend-option case_insensitive_whitelist='*'`
so your full command would look like
`./tools/sigmac -t xpack-watcher -c winlogbeat --backend-option keyword_field="" --backend-option case_insensitive_whitelist="*" rules/windows/process_creation/win_exploit_cve_2019_1388.yml`

2. to not use regex, but risk bypasses due to elastic removing free text search - use the following:
`./tools/sigmac -t xpack-watcher -c winlogbeat --backend-option keyword_field=""  rules/windows/process_creation/win_exploit_cve_2019_1388.yml`

**Comment by gsdt** [comment]
great answer! thank you so much.
